### ISSUE TITLE
Pl. add Silota to the list

### ISSUE THREAD

**Issue by gane5h** [thenaturalist/awesome-business-intelligence#1]
Hey Jan,

Appreciate it if you were able to add Silota (www.silota.com) to the Data Viz / Reporting > SQL list. 

We've also open-sourced all our "SQL recipes" that you can use for free with any of those alternate tools: http://www.silota.com/docs/recipes/

thanks,
Ganesh

**Comment by thenaturalist** [comment]
Hey Ganesh, 

Happily did so. Very cool what you're building & props for sharing the SQL recipes!
Like what you're doing!

Cheers
